version: '3'

services:
  customer:
    image: postgres
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: customer
    volumes:
      - ./docker-entrypoint-initdb.d.customer:/docker-entrypoint-initdb.d
    command:
      - "postgres"
      - "-c"
      - "max_prepared_transactions=100"


  account:
    image: postgres
    ports:
    - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: account
    volumes:
      - ./docker-entrypoint-initdb.d.account:/docker-entrypoint-initdb.d
    command:
      - "postgres"
      - "-c"
      - "max_prepared_transactions=100"

